version: "2"

services:
  consul:
    container_name: consul
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    restart: always
  registrator:
    container_name: registrator
    image: gliderlabs/registrator:latest
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: consul://consul:8500
    restart: always
    depends_on:
      - consul
  web:
    image: deis/mock-http-server
    ports:
      - 8080
    environment:
      SERVICE_8080_NAME: "web"
      SERVICE_8080_TAGS: "web"
    restart: always
    depends_on:
      - registrator
  haproxy:
    build: ./haproxy
    container_name: haproxy
    image: haproxy:latest
    ports:
      - 80
    depends_on:
      - web

networks:
  default:
